language: python
cache: pip
dist: xenial

jobs:
  include:
  - stage: Style Checking
    python: '3.7'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install black
    - pip install tgcli --upgrade
    script:
    - black setup.py tests/ tglogger/ -l 79
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "🥂 Style check passed for \`tglogger\`."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "✂️💥 Style checking failed for \`tglogger\`. [See](https://travis-ci.com/erayerdin/tglogger)."
  - stage: Testing
    python: '3.5'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install tgcli
    script:
    - pytest
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "🍻 \`tglogger\` works in Python 3.5."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "📦💥 \`tglogger\` failed in Python 3.5. [See](https://travis-ci.com/erayerdin/tglogger)."
  - stage: Testing
    python: '3.6'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install tgcli
    script:
    - pytest
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "🍻 \`tglogger\` works in Python3.6."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "📦💥 \`tglogger\` failed in Python 3.6. [See](https://travis-ci.com/erayerdin/tglogger)."
  - stage: Testing
    python: '3.7'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install tgcli --upgrade
    script:
    - pytest
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "🍻 \`tglogger\` works in Python 3.7."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "📦💥 \`tglogger\` failed in Python 3.7. [See](https://travis-ci.com/erayerdin/tglogger)."
  - stage: Covering / Deploy
    python: '3.7'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install tgcli --upgrade
    script:
    - pytest --cov-config .coveragerc --cov tgcli tests/
    - coveralls
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "🍾 \`tglogger\` coverage has passed."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "✂️💥 \`tglogger\` coverage has failed. [See](https://travis-ci.com/erayerdin/tglogger)."
    before_deploy:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "🚢 Deploying on PyPI..."
    deploy:
      provider: pypi
      user: erayerdin
      password:
        secure: "hzjEH6i5bmlxncQ97Df9ebnhIhLIZFPWNZpIUYrmte0vqLNUWNEKA9sF+Eb9C8bveMWbH8M10mj5tm4Oc/RUnEnOwTbjnrJxVgeoZZPT4RMMgTXcwc6WHlHCxEHheHcnozKUa6TkAdZtgmkKDHmqRvDyp9xhkkRTmTKyzHJYYiOIFa/p4TqGmtlH6Bj7m3YFwhPDbi8nPY4OVJ/wYdeywDFYMxxNQ3ugzM3xBDTWtn1u/9goeQRYKkNLc2jDztM9ZoFA+bKdFrBN0M38k1nmweJuVkvFk3+tAqN5+oRMYN9bE+AIAYWStOFJ9pfcAq/HOvZdWz9NGtX7fSm1l5R7H6x5XjevCB5aG9wkGokwoN5gpjfas6ndjaLBF2wkG+1wQ0ph2oaqswSLzD6CDs4XdNYwa5CvFnjLAGsNCx6J6riKDHhLjW5mca22reEe6ThNduxbP+Pz4WHcxXcTjoPvA2FGls69zrTmDyX1qXyQXGb6WoqijXio6QWU7fHnlSWAp/DrXW24tRhaySSdX0DwVkpn6hNFek0SGBjM+6dL34f5o0vQMwWpV9n3LnYXMEDiAGZc6P1uChTwl7d//wBSa+ZJzmUgyWPUigSz9Yb4lady+Idvxie+q21u9SLetvm/ktuhxDwdQn3RhcITAJ9LYFEm2neANapBg5vER2KNJjw="
      on:
        tags: true
